config/routes.rb
Rails.application.routes.draw do
  get "/interventions" => "interventions#new"
  resources :interventions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
 
get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'
get 'get_batteries_by_building/:building_id', to: 'batteries#get_batteries_by_building'
get 'get_columns_by_battery/:battery_id', to: 'columns#get_columns_by_battery'
get 'get_elevators_by_column/:column_id', to: 'elevators#get_elevators_by_column'

get "home/login"
get "/" => "home#index", :as => "root"
post "/" , to: "home#create"
get "residential" => "home#residential"
get "commercial" => "home#commercial"
get "quote" => "home#quote"
get "transcription" => "home#transcription"
get "transcribe" => "home#transcribe"
post "transcribe" => "voice#transcribe"

post "getData" => "quote#getData"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  invisible_captcha only: [:create]

  def index

      @lead = Lead.new

  end




  def create
    @lead = Lead.new(lead_params)
   
    if params[:lead][:upload]
      @lead.attachment = params[:lead][:upload].read
      @lead.filename = params[:lead][:upload].original_filename
    end

    if @lead.save
      ThankYouMailer.send_thank_you_email(@lead).deliver   
      create_lead_ticket
      # flash[:success] = "Your Quote has been successfully submitted    "
      redirect_to root_path, flash: {success: "Your Message has been successfully submitted"}
    end
  end

  def create_lead_ticket
    client = ZendeskAPI::Client.new do |config|
        config.url = ENV['ZENDESK_URL']
        config.username = ENV['ZENDESK_USERNAME']
        config.token = ENV['ZENDESK_TOKEN']
    end
    ZendeskAPI::Ticket.create!(client, 
        :subject => "#{params[:lead][:full_name].titleize} from #{params[:lead][:company_name].titleize}", 
        :comment => { 
            :value => "The contact #{params[:lead][:full_name].titleize} from company #{params[:lead][:company_name].titleize} can be reached at email  #{params[:lead][:email]} and at phone number #{params[:lead][:phone_number]}. 
            #{params[:lead][:department].titleize} has a project named #{params[:lead][:project_name].titleize} which would require contribution from Rocket Elevators.
            Project Description: #{params[:lead][:project_description]}\n\n
            Attached Message: #{params[:lead][:message]}\n\n
            The Contact uploaded an attachment"
        }, 
        :requester => { 
            "name": @lead.email, 
            "email": @lead.email,
        },
        :priority => "normal",
        :type => "question"
    )
  end
  


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @lead = Lead.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lead_params
    params.require(:lead).permit(:full_name,:email,:phone_number,:company_name,:project_name,:project_description,:department,:message)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<!-- FOOTER -->
			<footer id="footer">
				<div class="container">


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
								We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.
							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						<!-- col #2 -->
						<div class="col-md-4">
							<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

							<!-- Newsletter Form -->
							<p>Subscribe to Our Newsletter to get Important News & Offers</p>

							<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
									<span class="input-group-btn">
										<button class="btn btn-success" type="submit">Subscribe</button>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->


						</div>
						<!-- /col #2 -->

					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li><a href="#">Terms &amp; Conditions</a></li>
							<li>&bull;</li>
							<li><a href="#">Privacy</a></li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators
					</div>
				</div>

			</footer>
			<!-- /FOOTER -->

app/views/home/_form.html.erb
<%= form_tag("/getData") do  |f|%>
                
    <fieldset>
    

    <div class="row" id="client-info">
                    
        <div class="col-md-6" id="fName">
            
            <label for="lblFname">Company Name:</label>

            <%= text_field_tag :company_name, "", class: 'form-control' ,:required => true%>
            
        </div>
            
      <div class="col-md-6" id="phoneNumber">
         
      <label for="lblPhone">Phone Number:</label>
      <%= text_field_tag :phone_number, "", class: 'form-control' ,:required => true%>
    </div>
    <div class="col-md-6" id="email">
         
    <label for="lblEmail">Email:</label>
    <%= text_field_tag :email, "", class: 'form-control',:required => true %>

 </div>
        
        
          
        </div>
        <div class="row">
                <div class="col-md-8">
                    <!-- Drop Menu -->
                    <label for="buildings">Choose the coresponding building type:</label>

                    <select onchange="mainFunction()" name="buildings" id="buildingsType">
                    <option value="select">--- Please Select ---</option>
                    <option value="residential">Residential</option>
                    <option value="corporate">Corporate</option>
                    <option value="commercial">Commercial</option>
                    <option value="hybrid">Hybrid</option>
                    </select>
                    </div>
                
        </div>
                <!-- Show The options Fields -->
        <div class="row" id="step2" style="visibility: hidden">
            
                    <div class="col">

                        <label><b>These are our options for a</b> <span id="selectedBuilding"> </span> Building:</label>
                        
                        
                    </div>
                    </br>
        </div>
            <!-- Fields Sections -->
        <div class="row" id="input-fields" style="visibility: hidden">
                    
                        <div class="col-md-6" id="number-of-apartments" style="display: none;">
                         
                            <label for="lblApt">Number of number of Apartments:</label>
                            <input name="num_of_apts" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57"  onkeyup="actionListener()"  class="form-control" id="txtApt">
                    
                         </div>
                            
                        <div class="col-md-6" id="number-of-floors" style="display: none;" >
                            <label for="lblFloor">Number Floors:</label>
                            <input name="num_of_floors" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57"  onkeyup="actionListener()" placeholder="" class="form-control" id="txtFloor">
                            
                        </div>		
                        <div class="col-md-6" id="number-of-basement" style="display: none;" >
                            <label for="lblBasement">Number of Basement:</label>
                            <input name="num_of_basements" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57"  onkeyup="actionListener()" placeholder="" class="form-control" id="txtBasement">
                            
                        </div>	
                        <div class="col-md-6" id="number-of-companies" style="display: none;">
             
                            <label for="lblCompagnies">Number of Companies:</label>
                            <input name="num_of_companies" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57" onkeyup="actionListener()" placeholder="" class="form-control" id="txtCompanies">
                    
                         </div>
                            
                        <div class="col-md-6" id="number-of-parking-spots" style="display: none;" >
                            <label for="lblParking">Number Parking Spots:</label>
                            <input name="num_of_parking" type="number"  step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57" onkeyup="actionListener()" placeholder="" class="form-control" id="txtParking">
                            
                        </div>		
                        <div class="col-md-6" id="number-of-elevators" style="display: none;" >
                            <label for="lblElevators">Number of Elevators:</label>
                            <input name="num_of_elevators" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57"  onkeyup="actionListener()" placeholder="" class="form-control" id="txtElevators">
                            
                        </div>	
                        <div class="col-md-6" id="number-of-corporations" style="display: none;" >
                            <label for="lblCorporation">Number of Corporation:</label>
                            <input name="num_of_corporations" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57" onkeyup="actionListener()"  placeholder="" class="form-control" id="txtCorporation">
                            
                        </div>		
                        <div class="col-md-6" id="maximum-occupancy" style="display: none;" >
                            <label for="lblOccupancy">Maximum Occupancy:</label>
                            <input name="max_occupancy" type="number" step="1" onkeypress="return event.charCode >= 48 && event.charCode <=57" onkeyup="actionListener()" placeholder="" class="form-control" id="txtOccupancy">
                            
                        </div>	
                        <div class="col-md-6" id="business-hours" style="display: none;" >
                            <label for="lblHours">Business Hours:</label>
                            <input name="business_hours" type="number" step="1" maxlength="2" onkeypress="return event.charCode >= 48 && event.charCode <=57" onkeyup="actionListener()" class="form-control" id="txtHours">
                            
                        </div>		
                        
                        
        </div>
    </br></br>
    <div class="row">
            <div class="col-md-6" id="step3" style="visibility: hidden;">
                <h4>Please choose the type of the elevator:</h4>
        </div>
        <div class="col-md-6" id="step4" style="visibility: hidden;" >
            <h4>Summary:</h4>
    </div>
    </div>
    <div>
            <div class="row" id="input-fields-2" style="visibility: hidden;">
                
                 <div class="col-md-6" onclick="actionListener()">
                    
                    <label class="radio">
                        <input type="radio" name="radioSelect" id="standard" value="standard" checked>
                        <i></i> Standard
                    </label>
                    <label class="radio">
                        <input type="radio" name="radioSelect" id="premium" value="premium">
                        <i></i> Premium
                    </label>
                    <label class="radio">
                        <input type="radio" name="radioSelect" id="excelium"  value="excelium">
                        <i></i> Excelium
                    </label>
                </div>
                <div class="col-md-6" >
                        
                        <div style="display:flex; flex-direction: row;" id="elevator-amount">
                            <label for="lblAmntElevator">N. of Elevator:</label>
                            <input name="amntElevator" type="text" readonly="readonly"  class="form-control" id="txtAmntElevator">
                            
                        </div>
                        <div style="display:flex; flex-direction: row;" id="elevator-unit-price">
                            <label for="lblPriceElevator">Price per Elevator:</label>
                            <input name="priceElevator" type="text" readonly="readonly"   class="form-control" id="txtPriceElevator">
                            
                        </div>
                        <div style="display:flex; flex-direction: row;" id="elevator-total-price">
                            <label for="lblElevatorTotalPrice">Total Price for Elevators:</label>
                            <input name="priceElevatorTotal" type="text" readonly="readonly"   class="form-control" id="txtElevatorTotalPrice">
                            
                        </div>	
                        <div style="display:flex; flex-direction: row;" id="installation-fees">
                            <label for="lblInstallationFee">Installation Fee:</label>
                            <input name="installation_fee" type="text" readonly="readonly"   class="form-control" id="txtInstallationFee">
                            
                        </div>	
                        <div style="display:flex; flex-direction: row;" id="final-price">
                            <label for="lblTotal">Total Cost:</label>
                            
                            <input name="total_price" type="text"   readonly="readonly"  class="form-control" id="txtTotal">
                            
                        </div>		
                       
                </div>
                
            
            </div>
            <div id="input-fields-3" style="visibility: hidden;">
            <%= submit_tag "Submit" , class:"btn btn-warning btn-lg" ,:id => "btnSubmit"%>
            <button class="btn btn-warning btn-lg" onclick="emptyFields()">Reset</button>

            </div>  
            
    </div>
    
   
            
                
                
    </fieldset>

    
    <% end %>   

app/views/home/_header.html.erb
<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<a class="logo float-left scrollTo" href="<%= root_path %>">
						<%= image_tag "R2.png" %>
						</a>

						<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active"><!-- HOME -->
										<a href="/#">
											HOME
										</a>
									</li>
									<li><!-- SERVICES -->
										<a href="/#services">
											SERVICES
										</a>
									</li>
									<li><!-- WORK -->
										<a href="/#Portfolio">
											PORTFOLIO
										</a>
									</li>
									<li><!-- NEWS -->
										<a href="/#news">
											NEWS
										</a>
									</li>
									<li><!-- CLIENTS -->
										<a href="/#clients">
											CLIENTS
										</a>
									</li>
									<li><!-- CONTACT -->
										<a href="/#contact">
											CONTACT
										</a>
									</li>

									<% if user_signed_in? %>
										<li><%= link_to "INTERVENTIONS", '/interventions'%></li>
										<li><%= link_to 'BACK OFFICE', rails_admin_path %></li>
										<li><%= link_to 'SIGN OUT', destroy_user_session_path, :method => :delete  %></li>
									<% else %>
										<li><%= link_to 'SIGN IN', new_user_session_path%>
									<% end %></li>

								</ul>

							</nav>
						</div>


						</nav>
					</div>

				</div>

				<script async src="https://www.googletagmanager.com/gtag/js?id=G-CLV36D5E74"></script>
				<script>
				window.dataLayer = window.dataLayer || [];
				function gtag(){dataLayer.push(arguments);}
				gtag('js', new Date());

				gtag('config', 'G-CLV36D5E74');
				</script>
			</header>
			<!-- /Top Nav -->

		</div>


		<!-- Global site tag (gtag.js) - Google Analytics -->

app/views/home/commercial.html.erb
			<!-- HOME -->
			<section id="home">
						
				<div class="container text-center">
					
					<h1 class="m-0 fs-50 fw-300 wow fadeInUp" data-wow-delay="0.4s">Corporate Services</h1>

					<div class="row mt-100 text-left">

						<div class="col-md-8 col-sm-12 mb-30">
							<a><%= image_tag"AdobeStock_78149317.jpeg", :class => "img-fluid"%></a>
						</div>

						<div class="col-md-4 col-sm-12">
							<h3 class="fw-300">Product <span>Overview</span></h3>
						
							<p>Rocket Elevators Corporate Services is able to provide you with corporate grade elevators for your business or multi floor sky scraper, at affordable pricing.</p>
							<p>Go to our online portfolio to see some of the past corporate projects and award winning designs! Please contact us using the contact form for further information. </p>
							
							<hr />

							<ul class="list-unstyled list-icons">
								<li><i class="fa fa-check"></i> Same day quotes</li>
								<li><i class="fa fa-check"></i> Affordable pricing</li>
								<li><i class="fa fa-check"></i> professional team</li>
								<li><i class="fa fa-check"></i> experienced elevator installation team</li>
								<li><i class="fa fa-check"></i> Fastest elevator speeds</li>
							</ul>

						</div>
					</div>

				</div>

			</section>
			<!-- /HOME -->


			<!-- PRICING -->
			<section id="pricing">
				<div class="container">

					<header class="text-center mb-60">
						<h2>Elevator Pricing</h2>
						<p class="lead font-lato">Affordable prcing to get you started with elevator services in your business</p>
						<hr />
					</header>

					<div class="row" style="padding-left: 160px;">

						<div class="col-md-3 col-sm-3">
							
							<div class="price-clean">                                
								<h4>
									<sup>$</sup>7 565<em></em>
								</h4>
								<h5> Standard </h5>
								<hr />
								<p>Plus 10% installation fee</p>
								<hr />
								<a href="quote.html" class="btn btn-3d btn-teal">Get Quote</a>
							</div>
						
						</div>

						<div class="col-md-3 col-sm-3">
							
							<div class="price-clean">                                
								<h4>
									<sup>$</sup>12 345<em></em>
								</h4>
								<h5> Premium </h5>
								<hr />
								<p>Plus 13% installation fee</p>
								<hr />
								<a href="quote.html" class="btn btn-3d btn-teal">Get Quote</a>
							</div>
						
						</div>

						<div class="col-md-3 col-sm-3">
							
							<div class="price-clean">                                
								<h4>
									<sup>$</sup>15 400<em></em>
								</h4>
								<h5> Excelium </h5>
								<hr />
								<p>Plus 16% installation fee</p>
								<hr />
								<a href="quote.html" class="btn btn-3d btn-teal">Get Quote</a>
							</div>
						
						</div>

					</div>

				</div>
			</section>
			<!-- /PRICING -->



			<!-- TESTIMONIALS -->
			<section id="testimonials" class="alternate">
				<div class="container">

					<header class="text-center mb-60">
						<h2>Testimonials</h2>
						<p class="lead font-lato">See what some recent customer have said about our installation services</p>
						<hr />
					</header>

					<!-- 
						Note: remove class="rounded" from the img for squared image!
					-->
					<div class="row mb-60">
						<div class="col-md-4">
							<div class="testimonial testimonial-bordered p-15">
								<figure class="float-left">
									<%= image_tag"people/300x300/2-min.jpg", class: "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>They were very fast and pricing was reasonable. I had my new elevator installed within a few days!</p>
									<cite>
										Felicia Doe
									</cite>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="testimonial testimonial-bordered p-15">
								<figure class="float-left">
									<%= image_tag"people/300x300/1-min.jpg", class: "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>They came all the way out to our farm in the middle of nowhere to install the elevator. Fast and professional!</p>
									<cite>
										Joana Doe
									</cite>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="testimonial testimonial-bordered p-15">
								<figure class="float-left">
									<%= image_tag"people/300x300/6-min.jpg", class: "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>Very good serviuce. My apartment complex had it's 3 elevators installed and opporating within a few weeks!</p>
									<cite>
										Melissa Doe
									</cite>
								</div>
							</div>
						</div>
					</div>

					<!-- 
						Note: remove class="rounded" from the img for squared image!
					-->
					<ul class="row clearfix testimonial-dotted list-unstyled">
						<li class="col-md-4">
							<div class="testimonial">
								<figure class="float-left">
									<%= image_tag"people/300x300/2-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>If you need an elevator for your residence I would recommend Rocket Elevators for sure.</p>
									<cite>
										Joana Doe
									</cite>
								</div>
							</div>
						</li>
						<li class="col-md-4">
							<div class="testimonial">
								<figure class="float-left">
									<%= image_tag"people/300x300/6-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>Fast and reliable, professional installation team, fair pricing!</p>
									<cite>
										Melissa Doe
									</cite>
								</div>
							</div>
						</li>
						<li class="col-md-4">
							<div class="testimonial">
								<figure class="float-left">
									<%= image_tag"people/300x300/7-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>Very good! if I need another elevator job done I will use them again for sure!</p>
									<cite>
										Stephany Doe
									</cite>
								</div>
							</div>
						</li>
					</ul>

				</div>
			</section>
			<!-- /TESTIMONIALS -->


		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>


		<%# <!-- PRELOADER -->
		<div id="preloader">
			<div class="inner">
				<span class="loader"></span>
			</div>
		</div><!-- /PRELOADER --> %>

app/views/home/quote.html.erb
<!-- Request Form -->
<section id="requestForm">
    <div class="container">

        <header class="text-center mb-60">
            <h2>Request a quote</h2>
            <p class="lead font-lato">Rocket Elevator at your service 24h , 7 days a week.</p>
            <hr />
        </header>


        <div class="row">

            <!-- FORM -->
            <div class="col-md-8 col-sm-8">

                <h3>Let us know more about your project below:<strong></strong></h3>

                <%= render 'form' %>

            </div>
            <!-- /FORM -->

        

        </div>

    </div>
</section>
<!-- /CONTACT -->

app/views/home/residential.html.erb
<!-- HOME -->
			<section id="home">
						
				<div class="container text-center">
					
					<h1 class="m-0 fs-50 fw-300 wow fadeInUp" data-wow-delay="0.4s">Residential Services</h1>

					<div class="row mt-100 text-left">

						<div class="col-md-8 col-sm-12 mb-30">
							<a><%= image_tag"AdobeStock_124493370.jpeg", :class => "img-fluid"%></a>
						</div>

						<div class="col-md-4 col-sm-12">
							<h3 class="fw-300">Product <span>Overview</span></h3>
						
							<p>Rocket Elevators Residential Services is able to provide you with residential grade elevators for your multie level home or apartment complex, at affordable pricing.</p>
							<p>Go to our online portfolio to see some of the past residential projects we have worked on. Please contact us using the contact form for further information. </p>
							
							<hr />

							<ul class="list-unstyled list-icons">
								<li><i class="fa fa-check"></i> Same day quotes</li>
								<li><i class="fa fa-check"></i> Affordable pricing</li>
								<li><i class="fa fa-check"></i> professional team</li>
								<li><i class="fa fa-check"></i> experienced elevator installation team</li>
								<li><i class="fa fa-check"></i> Fastest home elevator speeds</li>
							</ul>

						</div>
					</div>

				</div>

			</section>
			<!-- /HOME -->


			<!-- PRICING -->
			<section id="pricing">
				<div class="container">

					<header class="text-center mb-60">
						<h2>Elevator Pricing</h2>
						<p class="lead font-lato">Affordable prcing to get you started with elevator services in your residence</p>
						<hr />
					</header>

					<div class="row" style="padding-left: 160px;">

						<div class="col-md-3 col-sm-3" >
							
							<div class="price-clean">                                
								<h4>
									<sup>$</sup>7 565<em></em>
								</h4>
								<h5> Standard </h5>
								<hr />
								<p>Plus 10% installation fee</p>
								<hr />
								<a href="quote.html" class="btn btn-3d btn-teal">Get Quote</a>
							</div>
						
						</div>

						<div class="col-md-3 col-sm-3">
							
							<div class="price-clean">                                
								<h4>
									<sup>$</sup>12 345<em></em>
								</h4>
								<h5> Premium </h5>
								<hr />
								<p>Plus 13% installation fee</p>
								<hr />
								<a href="quote.html" class="btn btn-3d btn-teal">Get Quote</a>
							</div>
						
						</div>

						<div class="col-md-3 col-sm-3">
							
							<div class="price-clean">                                
								<h4>
									<sup>$</sup>15 400<em></em>
								</h4>
								<h5> Excelium </h5>
								<hr />
								<p>Plus 16% installation fee</p>
								<hr />
								<a href="quote.html" class="btn btn-3d btn-teal">Get Quote</a>
							</div>
						
						</div>

					</div>

				</div>
			</section>
			<!-- /PRICING -->



			<!-- TESTIMONIALS -->
			<section id="testimonials" class="alternate">
				<div class="container">

					<header class="text-center mb-60">
						<h2>Testimonials</h2>
						<p class="lead font-lato">See what some recent customer have said about our installation services</p>
						<hr />
					</header>

					<!-- 
						Note: remove class="rounded" from the img for squared image!
					-->
					<div class="row mb-60">
						<div class="col-md-4">
							<div class="testimonial testimonial-bordered p-15">
								<figure class="float-left">
									<%= image_tag"people/300x300/2-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>They were very fast and pricing was reasonable. I had my new elevator installed within a few days!</p>
									<cite>
										Felicia Doe
									</cite>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="testimonial testimonial-bordered p-15">
								<figure class="float-left">
									<%= image_tag"people/300x300/1-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>They came all the way out to our farm in the middle of nowhere to install the elevator. Fast and professional!</p>
									<cite>
										Joana Doe
									</cite>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="testimonial testimonial-bordered p-15">
								<figure class="float-left">
									<%= image_tag"people/300x300/6-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>Very good serviuce. My apartment complex had it's 3 elevators installed and opporating within a few weeks!</p>
									<cite>
										Melissa Doe
									</cite>
								</div>
							</div>
						</div>
					</div>

					<!-- 
						Note: remove class="rounded" from the img for squared image!
					-->
					<ul class="row clearfix testimonial-dotted list-unstyled">
						<li class="col-md-4">
							<div class="testimonial">
								<figure class="float-left">
									<%= image_tag"people/300x300/2-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>If you need an elevator for your residence I would recommend Rocket Elevators for sure.</p>
									<cite>
										Joana Doe
									</cite>
								</div>
							</div>
						</li>
						<li class="col-md-4">
							<div class="testimonial">
								<figure class="float-left">
									<%= image_tag"people/300x300/6-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>Fast and reliable, professional installation team, fair pricing!</p>
									<cite>
										Melissa Doe
									</cite>
								</div>
							</div>
						</li>
						<li class="col-md-4">
							<div class="testimonial">
								<figure class="float-left">
									<%= image_tag"people/300x300/7-min.jpg", :class => "rounded"%>
								</figure>
								<div class="testimonial-content">
									<p>Very good! if I need another elevator job done I will use them again for sure!</p>
									<cite>
										Stephany Doe
									</cite>
								</div>
							</div>
						</li>
					</ul>

				</div>
			</section>
			<!-- /TESTIMONIALS -->