config/routes.rb
Rails.application.routes.draw do
  get "/interventions" => "interventions#new"
  resources :interventions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
 
get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'
get 'get_batteries_by_building/:building_id', to: 'batteries#get_batteries_by_building'
get 'get_columns_by_battery/:battery_id', to: 'columns#get_columns_by_battery'
get 'get_elevators_by_column/:column_id', to: 'elevators#get_elevators_by_column'

get "home/login"
get "/" => "home#index", :as => "root"
post "/" , to: "home#create"
get "residential" => "home#residential"
get "commercial" => "home#commercial"
get "quote" => "home#quote"
get "transcription" => "home#transcription"
get "transcribe" => "home#transcribe"
post "transcribe" => "voice#transcribe"

post "getData" => "quote#getData"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :customer
    belongs_to :employee
    belongs_to :author, class_name: "Employee"
    belongs_to :building
    belongs_to :battery
    belongs_to :column, optional: true
    belongs_to :elevator, optional: true
    

end 

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json

  def index
    @interventions = Intervention.all
  end
  
  # GET /interventions/1 or /interventions/1.json

  # GET /interventions/new
  def new
    #redirect_to root_path unless user_signed_in?
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    
    respond_to do |format|
      if @intervention.save
        format.html { redirect_to root_path, notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
        create_intervention_ticket()
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end



  def create_intervention_ticket
    client = ZendeskAPI::Client.new do |config|
        config.url = ENV['ZENDESK_URL']
        config.username = ENV['ZENDESK_USERNAME']
        config.token = ENV['ZENDESK_TOKEN']
    end
    ZendeskAPI::Ticket.create!(client, 
        :subject => "New Intervention has been created", 
        :comment => { 
            :value => "
            Customer: #{@intervention.customer.company_name}\n
            Building ID: #{@intervention.building_id}\n
            Battery ID: #{@intervention.battery_id}\n
            Column ID: #{@intervention.column_id}\n
            Elevator ID: #{@intervention.elevator_id}\n
            Employee: #{@intervention.employee.first_name} #{@intervention.employee.last_name}\n
            Description: #{@intervention.report}"
        }, 
        :requester => { 
            "name": @intervention.author.email, 
           
        },
        :priority => "normal",
        :type => "question"
    )
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
 

  # DELETE /interventions/1 or /interventions/1.json
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author_id, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :report)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container"> 

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.order(:company_name), :id, :company_name, {prompt: "Please Select"}, {class: 'customer-select'} %>
  </div>


  <div class="field buildings-field">
    <%= form.label :building_id %>
    <%= form.collection_select :building_id, Building.order(:id), :id, :id, {prompt: "Please Select"}, {class: 'buildings-select', required: true} %>
  </div>

  <div class="field batteries-field">
    <%= form.label :battery_id %>
    <%= form.collection_select :battery_id, Battery.order(:id), :id, :id, {prompt: "Please Select"}, {class: 'batteries-select', required: true} %>
  </div>

  <div class="field columns-field">
    <%= form.label :column_id %>
    <%= form.collection_select :column_id, Column.order(:id), :id, :id, {prompt: "Please Select"}, {class: 'columns-select'} %>
  </div>

  <div class="field elevators-field">
    <%= form.label :elevator_id %>
    <%= form.collection_select :elevator_id, Elevator.order(:id), :id, :id, {prompt: "Please Select"}, {class: 'elevators-select'} %>
  </div>

  <div class="field employees-field">
    <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.order(:email), :id, :email, {prompt: "Please Select"}, {class: 'employee-select', required: true} %>
  </div>


  <% if user_signed_in? %>
    <div class="field">
      <%= form.text_field :author_id, value:current_user.id, hidden: true  %>
    </div>
  <% else %>
    <div class="field">
      <%= form.text_field :author_id, value:1, hidden: true  %>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :report, "Description: " %>
    <%= form.text_field :report %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>


<% end %>


<%= javascript_include_tag "interventio" %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Employee</th>
      <th>Report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.customer_id %></td>
        <td><%= intervention.employee_id %></td>
        <td><%= intervention.report %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<div class="container">
    <h1>New Intervention</h1>

    <%= render 'form', intervention: @intervention %>

    <%= link_to 'Back', interventions_path %>

</div>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @intervention.customer_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @intervention.employee_id %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>